@authApi = http://api.hsfind.ir/auth
@address = http://api.hsfind.ir/hsfind
@lang = fa
@version = v1

@auth_cookie = accessToken=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.mftw_gQ4asoKoqiqii0qI6Pq6s8nlCorHDebuFSDtFLuz4JR6-rfhg.2pLTxn3PJoso8or9o3rHVQ.JnPjECeTPpL5DapRTujsJM8HnEx8_YvbGgdGW8wrjqXxj8unVS_lMCvtLC_U6PZSciTU3NU6e7K17-jvmv_BgofWUkLJEP8B7bPcdSshtvN3HpjERbZKnvWXeqIhJbz0iwUE5n8dEwLcRoABcZqEBDABx11F6wlzWOjvL_ZLPSlB_BaVCEitlMjEl3tdvfLNcS7zcsz9ILbkMz984xYcU-o2ES7XtnXsB686Nw3juFNoERGNmC6WzBbma9YmHOq62XZqqQueOXR51x4YJGYiK25GwpSTGi_M20Ag60iZFCs8rFrpigATxluSDn9ph_5_2Z_MlHJfaN6-yhNMg5La4EdFL8PHg6eaM7vn5gki2qFReSOLylBPz96eE6KItow-gaCnCv7HMBP8A1Ek-ss409Hh6RT60UG9UYD7ROWOowlM4s6JV2lLWU9LTAk39f4TWGSJL5XDPlgSqsBcQKK66KudtD-sG2Y0AXG8ifoBTj1BP13TnuFAFHyFYAmrCBo-TltdB1rw3njN-EuCp94YkZh0EJeR9dhdcZGhSH1uz2EVGBPgG6EBmdgJbu8ga35w6OLxV_hOWvAkkGlqVESIT1UjI-GRgNzsbRfGsoMPJbH21uEhewrU8B7nt7gES70e692QQF7zNnTSXcM_2oNH1wSyS4KsGi9yTnQz3RzQmx7Fp_r-r1v__6FQawJV_94qlgUfxz-4zB3TwFRMUbOzSoksJ3aZum5aJl9XnsSn34zGYDsqzp2uluN7cKyj6dSG.FltIgk7xeRbAGmHeLbRzdA; 



### دریافت لیست اینام ها

GET {{address}}/{{lang}}/{{version}}/info/enums
Content-Type: application/json

### دریافت لیست آیتم های یک اینام خاص

GET {{address}}/{{lang}}/{{version}}/info/enums/DeniedPartyType
Content-Type: application/json



### دریافت مشخصات درخواست دهنده

GET {{address}}/{{lang}}/{{version}}/info/client/?includeHeaders=false
Content-Type: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### ورود به سیستم

POST {{authApi}}/{{version}}/signin/password
Content-Type: application/json

{
    "userName": "Administrator",
    "password": "P@ssw0rd"
}

### خروج از سیستم

POST {{authApi}}/{{version}}/signout
Content-Type: application/json

