@address = http://api.inta.today/csm
@lang = fa
@version = v1
@auth_cookie = accessToken=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.FKN3MdoEy-4nu3qZs4eSH5jEwLz2b9Sda9V3zv45PkG1C_kZBr4SQw.Ezdq850b0poQpmm-CqXWUw.BvaWOEKhQnGxmuqEmEKlzc3vhNpXknbIEMnKnAYn7m4OpV8Ir2UIJk2PAy7oJJIE0eOYwhCPfwvpyEbIin9lomvvSLzddCrmOVArAV2ESoxD6AYHujFldd0lfzdd-6f4xGGuJSA9Gw-QcN60o9F_nFkvqSQVar8HaeHC04iVford6t7QHfnGQLnv-L2S7M5DdB_cfkmzUpqOSomfVyBIF-Dtwt6qzoOso-3TxeRX-vxlhSiIsussD6_Ila2JbLFSJW-o8jPINZSr1Vu4v-_Go8VCUp_C1WVJFH_2uVuI1t5y2MNOHjUU077xm8KtXOoD3xAAgX37O6V7LwNV64jHMWcOaBI47t-RqGYpTyIgTCvA8CeieFse82uVXPzhKcv-Vo1yMOBEDpI4tQ9qGIq71Odjxv1DERdIfQdPVqQBhj4qrtH7mUXJPXHjCma5-reMfoqQ7EFBhGraijh45GtsfdS2NeIgAl5I-tEeO7maTFPA6wsmN6mVaimJIE-DMVrXgOoj4oT3SRTUoZ5W2NtWni14vGEyH708gT0BWvGzS-z6yz-U4Yg8P6xa_orgjagTtUMGc_xuk_jjt7HFWbS8lcmQpWCuo6IR25mwtnE7y-hnQR4fKeKjoSwK5agHpDzRA8Wh07VYWcEqXDU70yNqWZBjbB9Lph-Yp-rpQ297R-YjiCA-ll_tvetkcr5dBCckPEsmwn39t-R9GWNNzaZ2kbWY3soMSlRiVGrZ5L3b_8GqiWK6tJblDwlYBgIjq183.hoGA57OXPpqeyyQ3o0gRFQ; 

##################################### مشتریان ########################################

### دریافت اطلاعات کشورها

GET {{address}}/{{lang}}/{{version}}/countries/all HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}
