//@address = http://localhost:6803/api
@address = http://api.inta.today/csm
@lang = fa
@version = v1
@auth_cookie = accessToken=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.qzahxamOu_ScpyZVnLiPCzp_DDY2Yq0PdPLy7T1EvoT1qAQtljQiMw.WdyK7_QZEyKSWTT-_tEtTQ.M6ZbcQGFEUlpLEuI6ZIAkGryM-eSijPNF8m6X9VmVdJsHLhUX_7yY9XK9xmZGEE5vvO6gvyqZ_QtBnX7JWX-IEOPVPfaYtHUsUiMGrzIdTlgYjyv4L6qFDbtzT7goraqFPEk1ZOOh3Se7O15F_buDhQt1JVA3RVCAdZpds5fhYgVoiS8dylnSrj0cdo0Yh2jgkXtmyuH_prfhg2H_m-yea1uHm3V71GXcbj_XFEPp6IziVQDs2zkVbBg0f7aA0O26zByTEnHIjzOOYA5GNWCI-PN99_fnKvWLUwCPb1FpjGIOMH0zihIj_-1IVtMOdKCRMxsUVWnfJAXMqUkGz5rc8V_dlTO-bCStPQE_TnGcoeAKmvhqxe7N2GYAZEOOAPEYPIxnI44II2_Mfr8aNie9wMV2TcNpTxlu8iIHuZQDSNu7MgjBu_Ldvib-Xh-WZ3z0pdKw_jq1HX_3D-hgDitIViHL6HH5tVU5aM_6aWW6dOvykKBnlzZa0nuUJ5j8jXTyRuqELPhL2-70iYcC2n4hHRlBMdRK1XxNxgUpTYMqg0AlnnWCpOdCojgroegEToFCHUrZfjLH-svOQSIASSVzlYFRPC5iVdrcsUXAUt-UuhyoWgZkY1IJ8vamJE8yPAUEo2UbLDyfYy2S_o4Az5IdI7B8_n_bwlLtfrA11GP4sWKHwdlONPFIxDdn2azlNv7F2MmmvKeChwf0hhdeOSxl0DLWkHjCZgWKMCmynXkdyq4RZNpLB1YA_6Z8XYxs-PL.2mgzseXq-vJCk8Nu3xWrEA;

##################################### مشتریان ########################################

### دریافت اطلاعات مشتری توسط خود مشتری

GET {{address}}/{{lang}}/{{version}}/customers HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

### دریافت اطلاعات یک مشتری توسط ادمین

GET {{address}}/{{lang}}/{{version}}/customers/ccee6a36-6b39-47ba-8628-8a22805c8a23 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

### دریافت اطلاعات همه مشتریان توسط ادمین

GET {{address}}/{{lang}}/{{version}}/customers/list?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

### دریافت اطلاعات مشتریان حقیقی توسط ادمین

GET {{address}}/{{lang}}/{{version}}/customers/list/individual?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

### دریافت اطلاعات مشتریان حقوقی توسط ادمین

GET {{address}}/{{lang}}/{{version}}/customers/list/legal?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### بروز رسانی اطلاعات مشتری حقوقی توسط خود مشتری

PUT {{address}}/{{lang}}/{{version}}/customers/legal HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


{
    "name": "inta",
    "establishDate": "2021-09-10T16:44:02.7274636+03:30",
    "email": "admin@inta.info",
    "phoneNumber": "+982171400358",
    "countryCode": 251,
    "country": "France",
    "city": "Paris",
    "address": "wall street of paris",
    "postalCode": "123456"
}


### بروز رسانی اطلاعات مشتری حقیقی توسط خود مشتری

PUT {{address}}/{{lang}}/{{version}}/customers/individual HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "firstName": "امیرحسام",
    "lastName": "کوهستانی",
    "gender": "Male",
    "birthDate": "2021-09-10T16:44:02.7274636+03:30",
    "email": "sinapsss@inta.info",
    "phoneNumber": "+982171400358",
    "countryCode": 251,
    "country": "France",
    "city": "Paris",
    "address": "wall street of paris",
    "postalCode": "123456"
}


### مشاهده نواقص پروفایل قبل از عملیاتی همچون خرید و ثبت سفارش

GET {{address}}/{{lang}}/{{version}}/customers/defects
Content-Type: application/json
Cookie: {{auth_cookie}}

