@address = http://localhost:6803/api
//@address = http://api.gimex.info/csm
@lang = fa
@version = v1
@auth_cookie = accessToken=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.1wbEAx8gqqtaoCguSUMEOqH2-h4vtwGGHlXxLo-6zVIJpybQpK6SKw.b7FQENDjRXnmVAJHjhqz9Q.rrs5k_FOF7vsjQdV0etLKrXfFN8bhwcokUQpDObg4s4yYgjx3fUhaHM68JYMFtdx6vP1sxP5TmN4cpP-633eCr5RSt6jV_j0LneA6zAxLFSyrNStNStm2LfCVHyfgTmoF503is7uNJ_1kALl07VuwOIgJeyQPntMWxBStgmhRK2_uctTqv_-XpZVtpd27llYckCxw2knO1UbbP9Sn0iGjaS57rNueS8-dOHtaYzvwwtLcj8hpYu0V84b0AKDj45OLVwrFPwMZpcg9fxSsmZdbHKElXzq9jCu-zNXb5jBMsG9QykAmIWbIxbxlLEBE6t1C2w-vefDZNC8rRtgeDrRg3TQxPA0kL7MWIas0ylTwQcStG4JhNJhjMNm03AXhdLRClDHPNtbU9cO6Skm8vid4KcJ3X8vYoEHsSBzSQPngoN8cYTN1juwBe5Zaa-THH7D8ZiqOLOonhKilW1RLaXlXyLYy1M2APD0-2MMvXQSo-tqwc5TuQGffulD4exX06klLbU34Whdx2g_52jqaM0GU0VKGp0hVJQ1ENxOFHW3ocxVDAtCK5Ce1KZO-pS2G86OIqX7gCloT_cbFxtMwehtBui3ZzFKeXTGZvxLQ09ymC_dRe-M1sbHoJ-1fOZejHueOh7fLNBgPZWm2DjneEd1zoJg9UqROk6DHcjN6gs9a5L4_70nCF5beGkdgxWABjb7wh9EzZmKGexcXxw95E0wEpp99A9n1XcABN92z0TCUjOi_T0_LJpPNFMyV1k7U9lm.UZgUjKUEC4Z2wrAYX6xJvA;

##################################### تخفیف ها ########################################

### دریافت اطلاعات یک تخفیف

GET {{address}}/{{lang}}/{{version}}/discounts HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### دریافت لیست تخفیف های عمومی (ادمین)

GET {{address}}/{{lang}}/{{version}}/discounts/public?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### دریافت لیست تخفیف های قابل اعمال برای یک کاربر خاص

GET {{address}}/{{lang}}/{{version}}/discounts/for-user/fb66bab4-92dc-4354-b9e9-93f2ee0638b0?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### چک کردن کد تخفیف و نمایش اطلاعات مبلغ بعد از اعمال تخفیف

POST {{address}}/{{lang}}/{{version}}/discounts/check HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "discountCode": "123456789",
    "userId": "fb66bab4-92dc-4354-b9e9-93f2ee0638b0",
    "planId": "75941a98-5f7f-416e-a869-0a4b6651de2d",
    "currencyType": "USD"
}

### ثبت کد تخفیف جدید توسط ادمین

POST {{address}}/{{lang}}/{{version}}/discounts HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "name": "winter sale offer",
    "code": "123",
    "feature":{
        "discountType": "SingleModule",
        "module": "Rules",
        "userId": null
    },
    "maxUsageCount": 1000,
    "maxDiscountAmount": 50,
    "currencyType": "USD",
    "discountPercent": 20,
    "expireDate": "2024-10-15T17:17:13.4855962+03:30",
    "isActive": true
}

### بروز رسانی اطلاعات یک تخفیف

PUT {{address}}/{{lang}}/{{version}}/discounts/fe7535bd-bdb5-4826-85b1-449c3104bade HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "name": "winter sale offer",
    "code": "123",
    "maxUsageCount": 1000,
    "maxDiscountAmount": 50,
    "currencyType": "USD",
    "discountPercent": 20,
    "expireDate": "2024-10-15T17:17:13.4855962+03:30",
}


### حذف یک تخفیف

DELETE {{address}}/{{lang}}/{{version}}/discounts/fe7535bd-bdb5-4826-85b1-449c3104bade HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### فعال کردن یک تخفیف

PUT {{address}}/{{lang}}/{{version}}/discounts/fe7535bd-bdb5-4826-85b1-449c3104bade/activate HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### غیر فعال کردن تخفیف

PUT {{address}}/{{lang}}/{{version}}/discounts/fe7535bd-bdb5-4826-85b1-449c3104bade/deactivate HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}



