//@address = http://localhost:6803/api
@address = http://api.inta.today/csm
@lang = fa
@version = v1
@auth_cookie = accessToken=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.WCb1mviXGq0R29bLN4juxhmuzPKtYZNGUOuXFnSPsbca-7AeIxrWtA.5LEazqK-P_wMIqZp_HmAOA.HcHcr91JvlQmoLfLRhFFwxJHx4CKTCMXSjVgEy6siZ2H9aA1BOBgJqkIbNRenXSi7C6LNBFhJDJd3GLru954mcq6SQnRs91xU-JGfFdPAPTSivttODiKfolb3DvHoP8EBAxHCyTV3e2vYgvO6OpX2XA_taCKhkj_t6jbaWulOyzPZadDuoquR6SjF3o8vviR6qGcmBkjfQrLwsnLRV-hIUGk4E-zMS6nhQRpAdJTFr3IK28GvFOCKGc-OtK7NdYhlevFfe_tJBmMmIasFFkQD2pibiydk9CDHLGo8PCLG3wMY3HcgP-fPMOSgrnJl6IUCz05_VKxg8eokHhCoEIu5e29ndW79c5QnuHuXyny0ytXQFZ4juTQKjLoQ7k6UwUdKI8QzXTukkX6DHyP2vSKQIYBzbnuEg9AogjJEkVLg8WgTwuct4udjlNRZovhcNtnPPqMo7oUNnj2N7DlCTA6jvRDEtIQNvm4bIK_BBd3fGiAO7u3kRDoBR43YAGch8jjM8Y8QxXiiuicgPrGmiY-33XIWRRkdR-nyljIY-lTZfNGwfwCgYS3ZyyN2XcYNBL13HHgAKitX-eysJWao8TQy2g7lgY7g2LlAVO8LdaC5RLqNZ2K-7KM1tL3_JGtWQiKFG0UCrSbTR4xeErI253hHf8F_ZpkB7uiGHOWBhR5gwowy142VrTEeYZSVO6TTIJ7RUQqKehSV218rMtLsL6FLlQtE9lreTYzxd0HtHN3UgxxpLCRDfseyq79Q4ieWAYQ.wfAT_5zVIpzTjuDkjWc0Mw;

##################################### طرح ها (پلن ها) ########################################

### دریافت پلن های فعال

GET {{address}}/{{lang}}/{{version}}/plans?currencyType=USD HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### دریافت اطللاعت یک طرح

GET {{address}}/{{lang}}/{{version}}/plans/55a171ba-9c17-4e08-ad23-4f248c430267 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### دریافت لیست همه طرح ها (فعال و غیرفعال)

GET {{address}}/{{lang}}/{{version}}/plans/all?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### ثبت پلن جدید

POST {{address}}/{{lang}}/{{version}}/plans HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "name": "rules-monthly",
    "description": "rules, monthly subscription, 1000 requests",
    "language": "En",
    "validityDays": 30,
    "requestsCount": 1000,
    "module": "Rules",
    "currencyType": "USD",
    "price": 80,
    "exhibitivePrice": 100,
    "isActive": true
}


### ویرایش پلن

PUT {{address}}/{{lang}}/{{version}}/plans/c76a8386-d219-496e-80b5-7167e34d75dd HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "name": "rules-monthly",
    "description": "rules, monthly subscription, 1000 requests",
    "validityDays": 30,
    "requestsCount": 1000,
    "module": "Rules"
}



### حذف یک پلن

DELETE {{address}}/{{lang}}/{{version}}/plans/51fe1246-6385-4755-84a5-bf41ffaa17fb HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### فعال کردن یک پلن

PUT {{address}}/{{lang}}/{{version}}/plans/c76a8386-d219-496e-80b5-7167e34d75dd/activate HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### غیر فعال کردن پلن

PUT {{address}}/{{lang}}/{{version}}/plans/c76a8386-d219-496e-80b5-7167e34d75dd/deactivate HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}


### ثبت قیمت برای پلن

POST {{address}}/{{lang}}/{{version}}/plans/55a171ba-9c17-4e08-ad23-4f248c430267/prices HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "currencyType": "IRR",
    "price": 2000000,
    "exhibitivePrice": 2500000
}


### حذف قیمت از پلن

DELETE {{address}}/{{lang}}/{{version}}/plans/c76a8386-d219-496e-80b5-7167e34d75dd/prices HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "currencyType": "IRR"
}


### ثبت ترجمه برای پلن

POST {{address}}/{{lang}}/{{version}}/plans/55a171ba-9c17-4e08-ad23-4f248c430267/translations HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "name": "قوانین - ماهیانه",
    "description": "ماژول قوانین - پرداخت ماهیانه - 1000 درخواست",
    "language": "Fa"
}


### حذف ترجمه از پلن

DELETE {{address}}/{{lang}}/{{version}}/plans/c76a8386-d219-496e-80b5-7167e34d75dd/translations HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "language": "Fa"
}



### دریافت پلن های مشتری لاگین شده

GET {{address}}/{{lang}}/{{version}}/plans/my HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "language": "Fa"
}

### دریافت پلن های یک مشتری خاص (توسط ادمین)

GET {{address}}/{{lang}}/{{version}}/plans/for-user/ab58016c-cbb3-45a0-a2bb-d5c6eec3714b HTTP/1.1
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "language": "Fa"
}
