@address = http://localhost:5502/api
//@address = http://api.gimex.info/content
@lang = fa
@version = v1

##################################### حساب های کاربری ########################################

### بررسی وجود یا عدم وجود حساب کاربری
GET {{address}}/{{version}}/accounts/user_name/exists HTTP/1.1
Content-Type: application/json


##################################### فعالیت های کاربر ########################################

### نمایش فعالیت های امنیتی کاربر (استفاده توسط کاربر لاگین شده)
GET {{address}}/{{version}}/activities?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json


### نمایش فعالیت های امنیتی کاربر درخواست شده (استفاده توسط ادمین)
GET {{address}}/{{version}}/activities/cfc438ee-e0fb-4f2f-869e-abb9059ce3f4?page=1&pageSize=20 HTTP/1.1
Content-Type: application/json

