@address = http://localhost:5502/api
//@address = http://api.gimex.info/content
@lang = fa
@version = v1

##################################### مدیریت رمز عبور دوعاملی ########################################


### فعال سازی رمز عبور دوعاملی
PUT {{address}}/{{version}}/twoFactor/befdd7b8-87a1-49e5-bfb1-5d3801162c7d/enable HTTP/1.1
Content-Type: application/json

### غیر فعال سازی رمز عبور دوعاملی
PUT {{address}}/{{version}}/twoFactor/befdd7b8-87a1-49e5-bfb1-5d3801162c7d/disable HTTP/1.1
Content-Type: application/json

### فعال سازی کد یک بارمصرف
### خروجی این ای پی آی یک تصویر کیوآر هست که کاربر باید آن را توسط نرم افزار اسکن کند
PUT {{address}}/{{version}}/twoFactor/befdd7b8-87a1-49e5-bfb1-5d3801162c7d/enable-otp HTTP/1.1
Content-Type: application/json

### غیر فعال سازی کد یک بارمصرف
PUT {{address}}/{{version}}/twoFactor/befdd7b8-87a1-49e5-bfb1-5d3801162c7d/disable-otp HTTP/1.1
Content-Type: application/json

### ارسال مجدد رمز عبور دوعاملی برای لاگین
PUT {{address}}/{{version}}/twoFactor/befdd7b8-87a1-49e5-bfb1-5d3801162c7d/resend-code HTTP/1.1
Content-Type: application/json



