@address = http://localhost:5502/api
//@address = http://api.gimex.info/content
@lang = fa
@version = v1

##################################### ورود به سیستم ########################################

### ورود کاربر توسط پسورد
### در صورتی که رمز دو عاملی فعال باشد بعد از این مرحله باید ورود توسط رمز دو عاملی نیز انجام شود

POST {{address}}/{{version}}/signin/password HTTP/1.1
Content-Type: application/json
{
    "userName": "administrator",
    "password": "P@ssword",
    "captchaId": "a1c3ba755fbe4345b44b811cd71e1609",
    "captchaCode": "123456"
}

### ورود توسط رمز دوعاملی
POST {{address}}/{{version}}/signin/two-factor HTTP/1.1
Content-Type: application/json

{
    "userId": "456424c3-4dc8-485b-8103-c9f7422d6b93",
    "verifyCode": "P@ssword",
    "CaptchaId": "a1c3ba755fbe4345b44b811cd71e1609",
    "CaptchaCode": "123456"
}

### تمدید مدت زمان انقضای توکن
POST {{address}}/{{version}}/signin/refresh HTTP/1.1
Content-Type: application/json

### خروج از سیستم
### این متد جهت استفاده در سناریوهای مختلف
POST {{address}}/{{version}}/signOut HTTP/1.1
Content-Type: application/json

##################################### کپچا ########################################

### تولید کپچای جدید (کپچای تولید شده بعد از یک زمان مشخص منقضی می شود)
GET {{address}}/{{version}}/captcha HTTP/1.1
Content-Type: application/json

### رفرش کردن کپچا (منقضی کردن کپچای فعلی و تولید کپچای جدید)
GET {{address}}/{{version}}/captcha/d68de833-4d27-4c29-9722-1237fe137e9a HTTP/1.1
Content-Type: application/json

### بررسی صحت کپچا
### معمولا در مواردی که در کامند نیاز به اطلاعات کپچا هست در ای پی آی مربوطه کپچا هم بررسی می شود
### و به جز مواری که یک سرویس بیرونی از کپچای این سرویس استفاده کند نیاز به صدا زدن این ای پی آی نیست
POST {{address}}/{{version}}/captcha HTTP/1.1
Content-Type: application/json

{
    "captchaId": "a1c3ba755fbe4345b44b811cd71e1609",
    "captchaCode": "123456"
}

##################################### چک کردن کاربر و توکن ########################################

### درصورتی که کاربر لاگین باشد اطلاعات کاربر لاگین شده را بازگشت می دهد
GET {{address}}/{{version}}/check/user HTTP/1.1
Content-Type: application/json

### دریافت وضعیت معتبر بودن توکن
GET {{address}}/{{version}}/check/token HTTP/1.1
Content-Type: application/json

##################################### مدیریت سشن ها ########################################

### دریافت سشن ها (لاگین های فعال کاربر)
GET {{address}}/{{version}}/sessions HTTP/1.1
Content-Type: application/json

### بستن یک سشن باز (لاگ آوت کاربر از یک سیستم دیگر)
POST {{address}}/{{version}}/sessions/d68de833-4d27-4c29-9722-1237fe137e9a/end HTTP/1.1
Content-Type: application/json

