@address = http://localhost:5502/api
//@address = http://api.gimex.info/content
@lang = fa
@version = v1

##################################### مدیریت رمز عبور ########################################

### تغییر رمز عبور توسط کاربر
POST {{address}}/{{version}}/password/change HTTP/1.1
Content-Type: application/json

{
    "currentPassword": "insecure_password",
    "newPassword": "very_secure_password",
    "confirmPassword": "very_secure_password",
}


### درخواست فراموشی رمز عبور
### پس از این ای پی آی، کدی که برای کاربر ارسال می شود باید به آدرس ریست ارسال شود
POST {{address}}/{{version}}/password/forget HTTP/1.1
Content-Type: application/json

{
    "userName": "alireza",
    "captchaId": "a1c3ba755fbe4345b44b811cd71e1609",
    "captchaCode": "123456"
}


### ریست کردن رمز عبور
### پس از درخواست فراموشی رمز عبور صدا زده می شود
POST {{address}}/{{version}}/password/reset/5acfcb7f-3725-4220-b4e0-1edf1ac0fd7b HTTP/1.1
Content-Type: application/json

{
    "userName": "alireza",
    "password": "very_secure_password",
    "confirmPassword": "very_secure_password",
    "captchaId": "a1c3ba755fbe4345b44b811cd71e1609",
    "captchaCode": "123456"
}


### ریست کردن رمز عبور توسط ادمین
### رمز جدید برای کاربر ارسال می شود (پیامک یا ایمیل)
POST {{address}}/{{version}}/password/reset/5acfcb7f-3725-4220-b4e0-1edf1ac0fd7b/by-admin HTTP/1.1
Content-Type: application/json


### تغییر رمز عبور به مقدار پیش فرض (توسط ادمین)
PUT {{address}}/{{version}}/password/default/5acfcb7f-3725-4220-b4e0-1edf1ac0fd7b HTTP/1.1
Content-Type: application/json


### بازگردانی رمز عبور کاربر پس از تبدیل به مقدار پیش فرض توسط ادمین
PUT {{address}}/{{version}}/password/restore/5acfcb7f-3725-4220-b4e0-1edf1ac0fd7b HTTP/1.1
Content-Type: application/json

